### ISSUE TITLE
[REQUEST] Adding kippo-graph

### ISSUE THREAD

**Issue by untergrundbiber** [dtag-dev-sec/kippo#1]
Hello
Would it be possible to add kippo-graph (https://github.com/ikoniaris/kippo-graph)?
That would be fantastic to replay and analyze ssh-sessions.

BTW: T-Pot is a really nice project, thanks for make it public!

**Comment by t3chn0m4g3** [comment]
kippo-graph is actually a great tool - we will check if it fits the roadmap for the next release. currently we are focussing primariliy on kibana and json logs for all honeypots.

thank you very much for your encouriging feedback on t-pot :smiley:
